on: push
name: Main Workflow
jobs:
  build:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@master
      - name: Setup go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: '1.24'
      - run:  go test -v -coverprofile cover.out
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: code-coverage-report
          path: ./

  sonarCloudTrigger:
    needs: build
    name: SonarCloud Trigger
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@master
      - name: Download code coverage results
        uses: actions/download-artifact@v4.2.1
        with:
          name: code-coverage-report
          path: ./
        # run: ls -al
      - name: Analyze with SonarCloud

        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./
